version: '3.9'
services:
    tibero5:
       hostname: 'tibero5sp1'
       build:
         context: .
       image: chrisryu/tibero5sp1 
       ports:
        - "8629-8649:8629-8649"
       volumes:
        - ./data:/tibero
        - ./license:/home/tibero/tibero5sp1/license
        - ./dist:/home/tibero/dist

